### ISSUE TITLE
4.85 cobra cfw??

### ISSUE THREAD

**Issue by razielsoulreaver** [obikuni/ObikuniMultiStore#2]
Wondering if you guys can make this work for cobra cfw rebug lite CEX 4.85 it crashes when its about to launch han to patch files

**Comment by Edw590** [comment]
Hey. See this: https://github.com/obikuni/ObikuniMultiStore/issues/3#issue-554780335 (it's not official though, but works normally).

**Comment by obikuni** [comment]
Well... I'm without a PC at this moment... Sorry. One day I will
