### ISSUE TITLE
Obikuni Multistore unofficial versions for 4.80(-?)-4.90(+?), CEX and DEX

### ISSUE THREAD

**Issue by Edw590** [obikuni/ObikuniMultiStore#3]
Hi! (I could write this in portuguese, but other people might want to read for any reason, so english)

As I noticed you didn't update the store, some months ago I updated it myself and kept it on a Discord server and some YouTube links of videos. But now it got back to my mind (I got in my MediaFire account and saw it has almost 1000 downloads for some reason) and thought it could be useful to tell you, if you don't want to have the time updating it, the version I updated has the HAN Toolbox Unofficial 0.8.1 base (I updated the official and put that name and it's on PSX-Place - https://www.psx-place.com/resources/han-toolbox-unofficial.870/), so it works from 4.81 to 4.85, CEX and DEX. Might be useful, as there are people on HAN that need it for 4.85, and others on CFW that need it for 4.85 too (like an issue here on your repository). If you'd like to use it or anything, or even if not, I'll just put it here in case anyone notices: http://www.mediafire.com/file/dg5m6rdoq7fmdnv/Obikuni-MultiStore-Full-V.1.2-Unofficial.pkg/file - Obikuni Multistore v1.2 Unofficial.

In any case, thanks for the amazing work on it!

PS: Just a quick note for anyone reading... Buy the games if you can, the developers deserve it! It's like saying thank you for them.

**UPDATE:** Just updated it to have the base of HAN Toolbox 0.9 Unofficial (the new version I released hours ago). It's here: https://www.mediafire.com/file/nczoobqcvt464q4/Obikuni-MultiStore-Full-V.1.3-Unofficial.pkg/file - Obikuni Multistore v1.3 Unofficial.

**UPDATE 2:** And updated it again, this time to have the base of HAN Toolbox 0.12 Unofficial (the newest version I've releaased with support from 4.81 to 4.88 and hopefully any newer versions). Here it is, in case anyone still would like to use the store: https://www.mediafire.com/file/zn9hnjdfqvezes1/Obikuni-MultiStore-Full-v1.4-Unofficial.pkg/file - Obikuni Multistore v1.4 Unofficial.

PS: don't use version 1.3 Unofficial. HAN Toolbox 0.9 came broken in some FW I don't remember for a mistake in the PS3Xploit website (and I didn't notice it because I run an older FW), but the newest HAN Toolbox should not have any bugs, and so will the store not have any either.

**UPDATE 3:** And here's another update. HAN Toolbox v0.14 Unofficial as base. CEX FWs 4.80(-?)-4.90(+?).

Permanent link: https://www.mediafire.com/file/zn9hnjdfqvezes1

The supported versions are the same as of the Unofficial versions of HAN Toolbox. Check on the PSX-Place link in the beginning.

**Comment by obikuni** [comment]
Hey, how's it going with you? I do not did any updates because I'll be without a PC for some time (I have no money to buy one new for now).
But, tnks for keeping my little project alive for who needs it.
Someday I'll go back to bring something new.
Until then, everyone can do whatever wants with the stores to give the community a continuation. It's all free to help.
Tnks again.
